var orderPlacementTemplate = {
    "_id" : ObjectId("5059ad213003d9b173222bdb"),
    "label" : "QTI2 Order Placement Interaction",
    "code" : "placement",
    "xmlData" : "<?xml version='1.0' encoding='UTF-8'?>\n<assessmentItem xmlns='http://www.imsglobal.org/xsd/imsqti_v2p1'\n                xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'\n                xsi:schemaLocation='http://www.imsglobal.org/xsd/imsqti_v2p1 http://www.imsglobal.org/xsd/imsqti_v2p1.xsd'\n                title='' adaptive='false' timeDependent='false'>\n\n\n    <responseDeclaration identifier='alphabet1' cardinality='ordered' baseType='identifier'>\n        <correctResponse>\n            <value>a</value>\n            <value>b</value>\n            <value>c</value>\n        </correctResponse>\n    </responseDeclaration>\n\n    <itemBody>\n        <orderInteraction responseIdentifier='alphabet1' shuffle='true' csOrderingType='placement'\n                          orientation='vertical'>\n            <prompt>Please select the letters of the alphabet and put them into ascending order:</prompt>\n            <simpleChoice identifier='a' fixed='true'>A</simpleChoice>\n            <simpleChoice identifier='b'>B</simpleChoice>\n            <simpleChoice identifier='c'>C</simpleChoice>\n            <simpleChoice identifier='n1'>1</simpleChoice>\n            <simpleChoice identifier='n2'>2</simpleChoice>\n            <simpleChoice identifier='n3'>3</simpleChoice>\n            <simpleChoice identifier='n4'>4</simpleChoice>\n        </orderInteraction>\n\n    </itemBody>\n\n\n</assessmentItem>\n\n\n"
};

var orderingTemplate = {
    "_id" : ObjectId("5059ad353004d9b123a22b2b"),
    "label" : "QTI2 Ordering Interaction",
    "code" : "order",
    "xmlData" : "<?xml version='1.0' encoding='UTF-8'?>\n<assessmentItem xmlns='http://www.imsglobal.org/xsd/imsqti_v2p1'\n                xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'\n                xsi:schemaLocation='http://www.imsglobal.org/xsd/imsqti_v2p1 http://www.imsglobal.org/xsd/imsqti_v2p1.xsd'\n                title='' adaptive='false' timeDependent='false'>\n\n\n    <responseDeclaration identifier='alphabet' cardinality='ordered' baseType='identifier'>\n        <correctResponse>\n            <value>a</value>\n            <value>b</value>\n            <value>c</value>\n            <value>d</value>\n            <value>e</value>\n            <value>f</value>\n            <value>g</value>\n            <value>h</value>\n        </correctResponse>\n    </responseDeclaration>\n\n    <itemBody>\n        <orderInteraction responseIdentifier='alphabet' shuffle='true'>\n            <prompt>Arrange letters of the alphabet:</prompt>\n            <simpleChoice identifier='a' fixed='true'>A</simpleChoice>\n            <simpleChoice identifier='b'>B</simpleChoice>\n            <simpleChoice identifier='c'>C</simpleChoice>\n            <simpleChoice identifier='d'>D</simpleChoice>\n            <simpleChoice identifier='e'>E</simpleChoice>\n            <simpleChoice identifier='f'>F</simpleChoice>\n            <simpleChoice identifier='g'>G</simpleChoice>\n            <simpleChoice identifier='h' fixed='true'>H</simpleChoice>\n        </orderInteraction>\n    </itemBody>\n\n</assessmentItem>\n\n\n"
};

db.templates.insert(orderPlacementTemplate);
db.templates.insert(orderingTemplate);