#!/usr/bin/env bash


# installation: 
# cd .git/hooks
# ln -s ../../hooks/pre-commit pre-commit

#git diff --cached --name-status

git diff --cached --name-only --diff-filter=ACM

echo "..."
git diff-index --cached HEAD
scalaVersion="2.10.2"
echo "format scala"
#./bin/scalariform -s=$scalaVersion --recurse app/
#./bin/scalariform -s=$scalaVersion --recurse modules/
