#!/usr/bin/env ruby

# installation: 
# cd .git/hooks
# ln -s ../../hooks/pre-commit pre-commit

module Utils

  REGEX = /.*[M|A]\s(.*\.scala)/

  def self.get_scala_changes(log)
    lines = log.split("\n")
    matches = lines.map{ |l| REGEX.match l}
    matches.select!{ |m| !m.nil?}
    out = matches.map{ |m| m[1]}
    out
  end
end

log = `git diff-index --cached HEAD`
files = Utils.get_scala_changes(log)
scalaVersion="2.10.2"

if files.length > 0
    cmd = "./bin/scalariform --test -s=#{scalaVersion} #{files.join(" ")}"
    output = `#{cmd}`

    format_cmd =  "./bin/scalariform -s=#{scalaVersion} #{files.join(" ")}"
    IO.popen('pbcopy', 'w').puts format_cmd
    if output.include? "[FAILED]"
        puts "--------------------------------------------------"
        puts "You need to format your scala code!"
        puts "run:"
        puts format_cmd
        puts "its been copied to your clipboard for your convenience"
        abort "--------------------------------------------------"
    end
end
