#!/usr/bin/env ruby
require 'uri'
file = ARGV[0]
puts file
text = File.readlines(file).each do |line|
  match = /.*\?q=(.*?)&.*/.match(line)

  unless match.nil?
    encoded = match[1] 
    decoded = URI.decode(encoded)
    puts decoded
  end
end


