#!/usr/bin/env ruby
require 'uri'
file = ARGV[0]
out = ARGV[1]
puts file

tokens = []


text = File.readlines(file).each do |line|
  match = /.*access_token=(.*?)"/.match(line)

  unless match.nil?
    encoded = match[1] 
    decoded = URI.decode(encoded)
    puts decoded
    tokens << decoded
  end
end

distinct = tokens.uniq

unless out.nil?
  File.open(out, "w+") do |f|
    f.puts(tokens)
  end
end
